name = "onshape-assistant-sync"
main = "src/index.js"
compatibility_date = "2026-03-01"

# Create these with:
#   wrangler kv namespace create "MERGE_PERMS"
#   wrangler kv namespace create "MERGE_PERMS" --preview
# Then paste the IDs below.
[[kv_namespaces]]
binding = "MERGE_PERMS"
id = "253b9336e6c64478a5f7e282c17e9cf7"
preview_id = "c76001f1e21c407ab4a334a7a38901b8"
